pipelines:
  bloody_pipeline:
    settings:
      decoder: raw
    input:
      type: file
      watching_dir: /home/daniel-orlov/Github/daniel-orlov/log-generator/fake-logs/
      offsets_file: /home/daniel-orlov/Github/daniel-orlov/log-generator/offsets.yaml
      filename_pattern: "*.log"
      persistence_mode: async
#    actions:
#      - type: parse_nginx_logs
#        match_fields:
#          level: /info/
    output:
      type: stdout